---

  - name: Check if OS is Debian-based (we do not support others)
    debug: "Check OS family"
    failed_when: ansible_os_family != "Debian"

  - name: Check if Ansible version is supported
    debug: "Check Ansible version"
    failed_when: ansible_version.full | version_compare('1.8', '<')
