---

  - name: 6.1 Ensure the X Window system is not installed (Scored)
    apt: name=xserver-xorg-core* purge=yes state=absent
    tags:
      - section6
      - section6.1

  - name: 6.2 Ensure Avahi Server is not enabled (check) (Scored)
    stat: path='/etc/init/avahi-daemon.conf'
    register: avahi_stat
    tags:
      - section6
      - section6.2

  - name: 6.2 Ensure Avahi Server is not enabled (Scored)
    lineinfile: >
        line='#start on (filesystem'
        state=present
        regexp='start on (filesystem'
        dest=/etc/init/.conf
    when: avahi_stat.stat.exists == True
    tags:
      - section6
      - section6.2

  - name: 6.3 Ensure print server is not enabled (check) (Not Scored)
    stat: path='/etc/init/cups.conf'
    register: cups_stat
    tags:
      - section6
      - section6.3

  - name: 6.3 Ensure print server is not enabled (Not Scored)
    lineinfile: >
        line='#start on (filesystem'
        state=present
        regexp='start on (filesystem'
        dest=/etc/init/cups.conf
    when: cups_stat.stat.exists == True
    tags:
      - section6
      - section6.3

  - name: 6.4.1 Ensure DHCP Server is not enabled (check) (Scored)
    stat: path='/etc/init/isc-dhcp-server.conf'
    register: dhcp_stat
    tags:
      - section6
      - section6.4
      - section6.4.1

  - name: 6.4.1 Ensure DHCP Server is not enabled (Scored)
    lineinfile: >
        line='#start on runlevel [2345]'
        state=present
        regexp='start on runlevel'
        dest=/etc/init/isc-dhcp-server.conf
    when: dhcp_stat.stat.exists == True
    tags:
      - section6
      - section6.4
      - section6.4.1

  - name: 6.4.2 Ensure DHCP Server is not enabled (check) (Scored)
    stat: path='/etc/init/isc-dhcp-server6.conf'
    register: dhcp6_stat
    tags:
      - section6
      - section6.4
      - section6.4.2

  - name: 6.4.2 Ensure DHCP Server is not enabled (Scored)
    lineinfile: >
        line='#start on runlevel [2345]'
        state=present
        regexp='start on runlevel'
        dest=/etc/init/isc-dhcp-server6.conf
    when: dhcp6_stat.stat.exists == True
    tags:
      - section6
      - section6.4
      - section6.4.2

  - name: 6.5.1 Configure Network Time Protocol (install) (NTP) (Scored)
    apt: name=ntp state=present
    tags:
      - section6
      - section6.5
      - section6.5.1

  - name: 6.5.2 Configure Network Time Protocol (restrict4) (NTP) (Scored)
    lineinfile: >
        dest='/etc/ntp.conf'
        line='restrict -4 default kod nomodify notrap nopeer noquery'
        regexp='^restrict -4 default'
        state=present
    tags:
      - section6
      - section6.5
      - section6.5.2

  - name: 6.5.3 Configure Network Time Protocol (restrict6) (NTP) (Scored)
    lineinfile: >
        dest='/etc/ntp.conf'
        line='restrict -6 default kod nomodify notrap nopeer noquery'
        regexp='^restrict -6 default'
        state=present
    tags:
      - section6
      - section6.5
      - section6.5.3

  - name: 6.5.4 Configure Network Time Protocol (server check) (NTP) (Scored)
    command: 'grep "^server" /etc/ntp.conf'
    register: ntp_server_rc
    changed_when: False
    tags:
      - section6
      - section6.5
      - section6.5.4

  - name: 6.5.4 Configure Network Time Protocol (server add) (NTP) (Scored)
    lineinfile: >
        dest='/etc/ntp.conf'
        line='server 0.fr.pool.ntp.org'
        state=present
    when: ntp_server_rc.rc == 1
    tags:
      - section6
      - section6.5
      - section6.5.4

  - name: 6.6 Ensure LDAP is not enabled (Not Scored)
    apt: name=slapd purge=yes
    tags:
      - section6
      - section6.6

  - name: 6.7.1 Ensure NFS and RPC are not enabled (stat) (Not Scored)
    stat: path=/etc/init/rpcbind-boot.conf
    register: nfs_rpc_rc
    tags:
      - section6
      - section6.7
      - section6.7.1

  - name: 6.7.2 Ensure NFS and RPC are not enabled (Not Scored)
    lineinfile: >
        dest=/etc/init/rpcbind-boot.conf
        line='#start on virtual-filesystems and net-device-up IFACE=lo'
        state=present
        regexp='start on virtual-filesystems and net'
    when: nfs_rpc_rc.stat.exists == True
    tags:
      - section6
      - section6.7
      - section6.7.2

  - name: 6.7.2 Ensure NFS and RPC are not enabled (rc.d) (Not Scored)
    service: >
        name=nfs-kernel-server
        enabled=no
    when: nfs_rpc_rc.stat.exists == True
    register: nfs_service_result
    failed_when: "nfs_service_result|failed and 'service not found' not in nfs_service_result.msg"
    tags:
      - section6
      - section6.7
      - section6.7.2

  - name: 6.8 Ensure DNS Server is not enabled (Not Scored)
    service: >
        name=bind9
        enabled=no
    tags:
      - section6
      - section6.8

  - name: 6.9 Ensure FTP Server is not enabled (Not Scored)
    service: >
      name=vsftpd
      enabled=no
    tags:
      - section6
      - section6.9

  - name: 6.10 Ensure HTTP Server is not enabled (Not Scored)
    service: >
        name=apache2
        enabled=no
    tags:
      - section6
      - section6.10

  - name: 6.11 Ensure IMAP and POP server is not enabled (Not Scored)
    service: >
      name=dovecot
      enabled=no
    tags:
      - section6
      - section6.11

  - name: 6.12 Ensure Samba is not enabled (Not Scored)
    service: >
      name=smbd
      enabled=no
    tags:
      - section6
      - section6.12

  - name: 6.13 Ensure HTTP Proxy Server is not enabled (Not Scored)
    service: >
      name=squid3
      enabled=no
    tags:
      - section6
      - section6.13

  - name: 6.14 Ensure SNMP Server is not enabled (Not Scored)
    service: >
        name=snmpd
        enabled=no
    tags:
      - section6
      - section6.14

  - name: 6.15 Configure Mail Transfer Agent for Local-Only Mode (Scored)
    lineinfile: >
        dest=/etc/postfix/main.cf
        line='inet_interfaces = localhost'
        state=present
    tags:
      - section6
      - section6.15

  - name: 6.16 Ensure rsync service is not enabled (Scored)
    lineinfile: >
        dest='/etc/default/rsync'
        regexp='RSYNC_ENABLE'
        line='RSYNC_ENABLE=false'
    tags:
      - section6
      - section6.16

  - name: 6.17 Ensure Biosdevname is not enabled (Scored)
    apt: name=biosdevname purge=yes
    tags:
      - section6
      - section6.17
