---

  - name: 1.1.1 Install Updates, Patches and Additional Security Software (NotScored)
    apt: update_cache=yes
    tags:
      - section1
      - section1.1
      - section1.1.1

  - name: 1.1.2 Install Updates, Patches and Additional Security Software (NotScored)
    apt: upgrade=yes
    tags:
      - section1
      - section1.1
      - section1.1.2
